version: '3'

services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: LearnHubDatabase
      MYSQL_USER: learnhub
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data/database:/var/lib/mysql
    ports:
      - "3306:3306"

  learnhub:
    depends_on:
      - database
    build:
      context: ./LearnHub-Backend
      dockerfile: ./Dockerfile
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DOMAIN: ${DOMAIN}
      PROFILES: ${PROFILES}

  learnhub-server:
    depends_on:
      - learnhub
    build: 
      context: ./http-server
      dockerfile: ./Dockerfile
    ports:
      - 8080:80


